// data.ts
// Autors: Kristofers Semjonovs

import bcrypt from 'bcryptjs'
import { User } from './models/userModel'
import { Product } from './models/productModel'

// Fails ar sākuma datiem, šie dati tiek pievienoti datubāzei tās izveides brīdī

export const sampleProducts: Product[] = [
  {
    name: 'Gigabyte RTX 4090',
    slug: 'gigabyte-rtx-4090',
    category: 'GPU',
    image: '../images/p1.jpg',
    price: 1200,
    countInStock: 10,
    brand: 'Gigabyte',
    rating: 0,
    numReviews: 0,
    description: 'powerful graphics card',
  },
  {
    name: 'Gigabyte Aorus RTX 4090',
    slug: 'gigabyte-aorus-rtx-4090',
    category: 'GPU',
    image: '../images/p2.jpg',
    price: 1400,
    countInStock: 7,
    brand: 'Gigabyte',
    rating: 0,
    numReviews: 0,
    description: 'very powerful graphics card',
  },
  {
    name: 'Asus ROG Strix RTX 4090',
    slug: 'asus-rog-strix-rtx-4090',
    category: 'GPU',
    image: '../images/p3.jpg',
    price: 1800,
    countInStock: 3,
    brand: 'Asus',
    rating: 0,
    numReviews: 0,
    description: 'premium quality graphics card',
  },
  {
    name: ' MSI RTX 4090',
    slug: 'msi-rtx-4090',
    category: 'GPU',
    image: '../images/p4.jpg',
    price: 1300,
    countInStock: 12,
    brand: 'MSI',
    rating: 0,
    numReviews: 0,
    description: 'powerful graphics card',
  },
  {
    name: ' GIGABYTE RTX 4080',
    slug: 'gigabyte-rtx-4080',
    category: 'GPU',
    image: '../images/p5.jpg',
    price: 1000,
    countInStock: 2,
    brand: 'Gigabyte',
    rating: 0,
    numReviews: 0,
    description: 'pretty powerful graphics card',
  },
  {
    name: ' MSI RTX 4070 Ti SUPER',
    slug: 'msi-rtx-4070-ti-super',
    category: 'GPU',
    image: '../images/p6.jpg',
    price: 900,
    countInStock: 9,
    brand: 'MSI',
    rating: 0,
    numReviews: 0,
    description: 'decently powerful graphics card',
  },
  {
    name: ' Asus ProArt rtx 4070 Ti',
    slug: 'asus-proart-rtx-4070-ti',
    category: 'GPU',
    image: '../images/p7.jpg',
    price: 800,
    countInStock: 10,
    brand: 'Gigabyte',
    rating: 0,
    numReviews: 0,
    description: 'elegant and powerful graphics card',
  },
  {
    name: 'GIGABYTE GT 1030',
    slug: 'gigabyte-gt-1030',
    category: 'GPU',
    image: '../images/p8.jpg',
    price: 100,
    countInStock: 25,
    brand: 'Gigabyte',
    rating: 0,
    numReviews: 0,
    description: 'not so powerful graphics card',
  },
  {
    name: 'Intel Core Ultra 5 245k',
    slug: 'intel-core-ultra-5',
    category: 'CPU',
    image: '../images/p9.jpg',
    price: 300,
    countInStock: 12,
    brand: 'Intel',
    rating: 0,
    numReviews: 0,
    description: '6 performance cores, 8 efficiency cores',
  },
  {
    name: 'Intel Core Ultra 7 265k',
    slug: 'intel-core-ultra-7',
    category: 'CPU',
    image: '../images/p10.jpg',
    price: 400,
    countInStock: 10,
    brand: 'Intel',
    rating: 0,
    numReviews: 0,
    description: '8 performance cores, 12 efficiency cores',
  },
  {
    name: 'AMD Ryzen 7 9800x3d',
    slug: 'amd-ryzen-7-9800x3d',
    category: 'CPU',
    image: '../images/p11.jpg',
    price: 450,
    countInStock: 7,
    brand: 'AMD',
    rating: 0,
    numReviews: 0,
    description: '8 cores, 96MB L3 Cache',
  },
  {
    name: 'AMD Ryzen 5 7600x',
    slug: 'amd-ryzen-5-7600x',
    category: 'CPU',
    image: '../images/p12.jpg',
    price: 250,
    countInStock: 32,
    brand: 'AMD',
    rating: 0,
    numReviews: 0,
    description: '6 cores, 32MB L3 Cache',
  },
  {
    name: 'Intel Core i9-14900KF',
    slug: 'intel-core-i9-14900kf',
    category: 'CPU',
    image: '../images/p21.jpg',
    price: 550,
    countInStock: 2,
    brand: 'Intel',
    rating: 0,
    numReviews: 0,
    description: '8 performance cores, 16 efficiency cores',
  },
  {
    name: 'Intel Core i7-13700K',
    slug: 'intel-core-i7-13700k',
    category: 'CPU',
    image: '../images/p22.jpg',
    price: 350,
    countInStock: 5,
    brand: 'Intel',
    rating: 0,
    numReviews: 0,
    description: '8 performance cores, 8 efficiency cores',
  },
  {
    name: 'AMD Ryzen 7 7800X3D',
    slug: 'amd-ryzen-7-7800x3d',
    category: 'CPU',
    image: '../images/p23.jpg',
    price: 450,
    countInStock: 12,
    brand: 'AMD',
    rating: 0,
    numReviews: 0,
    description: '8 cores, 96MB L3 Cache',
  },
  {
    name: 'AMD Ryzen 7 5700X3D',
    slug: 'amd-ryzen-7-5700x3d',
    category: 'CPU',
    image: '../images/p24.jpg',
    price: 250,
    countInStock: 1,
    brand: 'AMD',
    rating: 0,
    numReviews: 0,
    description: '8 cores, 96MB L3 Cache',
  },
  {
    name: 'Asus ROG STRIX Z790-E GAMING WIFI',
    slug: 'asus-rog-strix-z90-e-gaming-wifi',
    category: 'MOBO',
    image: '../images/p13.jpg',
    price: 550,
    countInStock: 12,
    brand: 'Asus',
    rating: 0,
    numReviews: 0,
    description: 'Compatible with 12th, 13th and 14th gen intel processors',
  },
  {
    name: 'Gigabyte Z790 S DDR4',
    slug: 'gigabyte-z790-s-ddr4',
    category: 'MOBO',
    image: '../images/p14.jpg',
    price: 250,
    countInStock: 23,
    brand: 'Gigabyte',
    rating: 0,
    numReviews: 0,
    description: 'Compatible with ddr4 ram and Intel lga 1700 socket',
  },
  {
    name: 'Asus PRIME X870-P',
    slug: 'asus-prime-x870-p',
    category: 'MOBO',
    image: '../images/p15.jpg',
    price: 322.76,
    countInStock: 8,
    brand: 'Asus',
    rating: 0,
    numReviews: 0,
    description: 'Compatible with AMD am5 platform and ddr5 ram',
  },
  {
    name: 'Asus ROG STRIX X870-A GAMING WIFI',
    slug: 'asus-rog-strix-x870-a-gaming-wifi',
    category: 'MOBO',
    image: '../images/p16.jpg',
    price: 486.24,
    countInStock: 3,
    brand: 'Asus',
    rating: 0,
    numReviews: 0,
    description: 'Socket: am5, Ram: ddr5, rgb: yes',
  },
  {
    name: 'Gigabyte B650 UD AX',
    slug: 'gigabyte-b650-ud-ax',
    category: 'MOBO',
    image: '../images/p17.jpg',
    price: 186.74,
    countInStock: 13,
    brand: 'Gigabyte',
    rating: 0,
    numReviews: 0,
    description: 'Socket: am5, Ram: ddr5, rgb: no',
  },
  {
    name: 'MSI PRO B650-S WIFI',
    slug: 'msi-pro-b650-s-wifi',
    category: 'MOBO',
    image: '../images/p18.jpg',
    price: 206.12,
    countInStock: 10,
    brand: 'MSI',
    rating: 0,
    numReviews: 0,
    description: 'Socket: am5, Ram: ddr5, wifi: yes',
  },
  {
    name: 'Asrock B760 Pro RS D4',
    slug: 'asrock-b760-pro-rs-d4',
    category: 'MOBO',
    image: '../images/p19.jpg',
    price: 230.72,
    countInStock: 9,
    brand: 'Asrock',
    rating: 0,
    numReviews: 0,
    description: 'Socket: lga1700, Ram: ddr4, wifi: no',
  },
  {
    name: 'Asus PRIME B760-PLUS D4',
    slug: 'asus-prime-b760-plus-d4',
    category: 'MOBO',
    image: '../images/p20.jpg',
    price: 210.12,
    countInStock: 4,
    brand: 'Asus',
    rating: 0,
    numReviews: 0,
    description: 'Socket: lga1700, Ram: ddr4, wifi: no',
  },
]

export const sampleUsers: User[] = [
  {
    name: 'Joe',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },
  {
    name: 'John',
    email: 'user@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
]
